### ISSUE TITLE
Add from_geojson() Methods to Typology Class

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly-uwg#17]
Geojsons are available for a lot of cities and we should support methods to create Dragonfly objects from them.

**Comment by AntoineDao** [comment]
Here's some notes to help someone get started with this.

**Comment by chriswmackey** [comment]
This has now been addressed by virtue of the fact that dragonfly-uwg is now a full extension of dragonfly and dragonfly-core contains methods for serialization from geoJSON.
